/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWebcamRouteImport } from './routes/demo/webcam'
import { Route as DemoTimeSlidersRouteImport } from './routes/demo/time-sliders'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPomodoroRouteImport } from './routes/demo/pomodoro'
import { Route as DemoNotebookRouteImport } from './routes/demo/notebook'
import { Route as DemoGradientRouteImport } from './routes/demo/gradient'
import { Route as DemoGiveawayRouteImport } from './routes/demo/giveaway'
import { Route as DemoEyesRouteImport } from './routes/demo/eyes'
import { Route as DemoCubesRouteImport } from './routes/demo/cubes'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoClipboardRouteImport } from './routes/demo/clipboard'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWebcamRoute = DemoWebcamRouteImport.update({
  id: '/demo/webcam',
  path: '/demo/webcam',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTimeSlidersRoute = DemoTimeSlidersRouteImport.update({
  id: '/demo/time-sliders',
  path: '/demo/time-sliders',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPomodoroRoute = DemoPomodoroRouteImport.update({
  id: '/demo/pomodoro',
  path: '/demo/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNotebookRoute = DemoNotebookRouteImport.update({
  id: '/demo/notebook',
  path: '/demo/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGradientRoute = DemoGradientRouteImport.update({
  id: '/demo/gradient',
  path: '/demo/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGiveawayRoute = DemoGiveawayRouteImport.update({
  id: '/demo/giveaway',
  path: '/demo/giveaway',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEyesRoute = DemoEyesRouteImport.update({
  id: '/demo/eyes',
  path: '/demo/eyes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCubesRoute = DemoCubesRouteImport.update({
  id: '/demo/cubes',
  path: '/demo/cubes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClipboardRoute = DemoClipboardRouteImport.update({
  id: '/demo/clipboard',
  path: '/demo/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/clipboard': typeof DemoClipboardRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/cubes': typeof DemoCubesRoute
  '/demo/eyes': typeof DemoEyesRoute
  '/demo/giveaway': typeof DemoGiveawayRoute
  '/demo/gradient': typeof DemoGradientRoute
  '/demo/notebook': typeof DemoNotebookRoute
  '/demo/pomodoro': typeof DemoPomodoroRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/time-sliders': typeof DemoTimeSlidersRoute
  '/demo/webcam': typeof DemoWebcamRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/clipboard': typeof DemoClipboardRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/cubes': typeof DemoCubesRoute
  '/demo/eyes': typeof DemoEyesRoute
  '/demo/giveaway': typeof DemoGiveawayRoute
  '/demo/gradient': typeof DemoGradientRoute
  '/demo/notebook': typeof DemoNotebookRoute
  '/demo/pomodoro': typeof DemoPomodoroRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/time-sliders': typeof DemoTimeSlidersRoute
  '/demo/webcam': typeof DemoWebcamRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/clipboard': typeof DemoClipboardRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/cubes': typeof DemoCubesRoute
  '/demo/eyes': typeof DemoEyesRoute
  '/demo/giveaway': typeof DemoGiveawayRoute
  '/demo/gradient': typeof DemoGradientRoute
  '/demo/notebook': typeof DemoNotebookRoute
  '/demo/pomodoro': typeof DemoPomodoroRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/time-sliders': typeof DemoTimeSlidersRoute
  '/demo/webcam': typeof DemoWebcamRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/clipboard'
    | '/demo/convex'
    | '/demo/cubes'
    | '/demo/eyes'
    | '/demo/giveaway'
    | '/demo/gradient'
    | '/demo/notebook'
    | '/demo/pomodoro'
    | '/demo/tanstack-query'
    | '/demo/time-sliders'
    | '/demo/webcam'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/clipboard'
    | '/demo/convex'
    | '/demo/cubes'
    | '/demo/eyes'
    | '/demo/giveaway'
    | '/demo/gradient'
    | '/demo/notebook'
    | '/demo/pomodoro'
    | '/demo/tanstack-query'
    | '/demo/time-sliders'
    | '/demo/webcam'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/clipboard'
    | '/demo/convex'
    | '/demo/cubes'
    | '/demo/eyes'
    | '/demo/giveaway'
    | '/demo/gradient'
    | '/demo/notebook'
    | '/demo/pomodoro'
    | '/demo/tanstack-query'
    | '/demo/time-sliders'
    | '/demo/webcam'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoClipboardRoute: typeof DemoClipboardRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoCubesRoute: typeof DemoCubesRoute
  DemoEyesRoute: typeof DemoEyesRoute
  DemoGiveawayRoute: typeof DemoGiveawayRoute
  DemoGradientRoute: typeof DemoGradientRoute
  DemoNotebookRoute: typeof DemoNotebookRoute
  DemoPomodoroRoute: typeof DemoPomodoroRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTimeSlidersRoute: typeof DemoTimeSlidersRoute
  DemoWebcamRoute: typeof DemoWebcamRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/webcam': {
      id: '/demo/webcam'
      path: '/demo/webcam'
      fullPath: '/demo/webcam'
      preLoaderRoute: typeof DemoWebcamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/time-sliders': {
      id: '/demo/time-sliders'
      path: '/demo/time-sliders'
      fullPath: '/demo/time-sliders'
      preLoaderRoute: typeof DemoTimeSlidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pomodoro': {
      id: '/demo/pomodoro'
      path: '/demo/pomodoro'
      fullPath: '/demo/pomodoro'
      preLoaderRoute: typeof DemoPomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/notebook': {
      id: '/demo/notebook'
      path: '/demo/notebook'
      fullPath: '/demo/notebook'
      preLoaderRoute: typeof DemoNotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/gradient': {
      id: '/demo/gradient'
      path: '/demo/gradient'
      fullPath: '/demo/gradient'
      preLoaderRoute: typeof DemoGradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/giveaway': {
      id: '/demo/giveaway'
      path: '/demo/giveaway'
      fullPath: '/demo/giveaway'
      preLoaderRoute: typeof DemoGiveawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/eyes': {
      id: '/demo/eyes'
      path: '/demo/eyes'
      fullPath: '/demo/eyes'
      preLoaderRoute: typeof DemoEyesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cubes': {
      id: '/demo/cubes'
      path: '/demo/cubes'
      fullPath: '/demo/cubes'
      preLoaderRoute: typeof DemoCubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clipboard': {
      id: '/demo/clipboard'
      path: '/demo/clipboard'
      fullPath: '/demo/clipboard'
      preLoaderRoute: typeof DemoClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoClipboardRoute: DemoClipboardRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoCubesRoute: DemoCubesRoute,
  DemoEyesRoute: DemoEyesRoute,
  DemoGiveawayRoute: DemoGiveawayRoute,
  DemoGradientRoute: DemoGradientRoute,
  DemoNotebookRoute: DemoNotebookRoute,
  DemoPomodoroRoute: DemoPomodoroRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTimeSlidersRoute: DemoTimeSlidersRoute,
  DemoWebcamRoute: DemoWebcamRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
